### ISSUE TITLE
Potential memory leakage

### ISSUE THREAD

**Issue by florian6973** [mmcdermott/MEDS_Tabular_AutoML#144]
Hi!

I have been using meds-tab on large datasets, with several workers, and I noticed that over time the full RAM gets occupied. I need to manually kill the python processes to get it freed (CTRL+C is not enough), clear the locks, and then restart it.
<details><summary>Lock cleaning</summary>

```python
files = glob.glob(os.path.join(path, '**', '.*.npz_cache'), recursive=True)
k = 0
for file in files:
    try:
        # remove only if name.npz does not exist when .name.npz_cache exists
        base_name = os.path.splitext(file)[0].replace('/.', '/') 
        if os.path.exists(base_name + '.npz'):
            continue
        k += 1
        shutil.rmtree(file)  # Remove the directory containing the cache file
        print(f"Removed cache file: {file}")
    except Exception as e:
        print(f"Error removing {file}: {e}")
print(f"Total cache files removed: {k}")
```

</details>
However, the same memory leakage happens over time (about 1 hour to fill the RAM), after restarting it.

I have been using the following command line:
```
[
    "meds-tab-tabularize-time-series",
    "--multirun",
    f"worker=range(0,{N_PARALLEL_WORKERS})",
    "hydra/launcher=joblib",
    f"input_dir={os.path.join(REDSHARD_DIR, 'data')}",
    f"output_dir={os.path.join(OUTPUT_MODEL_DIR, task)}",
    "do_overwrite=False",
    f"input_label_dir={os.path.join(TASKS_DIR, task)}",
    "tabularization.aggs=[code/count,value/count,value/sum,value/sum_sqd,value/min,value/max]",
    "tabularization.window_sizes=[1d,7d,30d,60d,365d,full]"
]
```

Any insights or help would be very much appreciated, thanks!

**Comment by florian6973** [comment]
After running memray on a single process, for 2 aggregation files (I stopped after), we can clearly see the leak, with an always-increasing heap size (small drop when changing file)

<img width="1203" alt="Image" src="https://github.com/user-attachments/assets/fc6ab542-8cc1-4beb-a651-e9e8eda766bc" />

**Comment by mmcdermott** [comment]
@florian6973, this memory utilization is continuing after you kill the processes? Can you check with `top` or `htop` and see if there are zombie processes running from MEDS-Tab after you kill them?

Also, is this a memory leak (e.g., memory is being used unexpectedly) or is it just that the work that is being done is unexpectedly memory intensive?

@Oufattole or @teyaberg, any insights here?

**Comment by florian6973** [comment]
When I was stopping the meds-tab command with CTRL+C only, the memory was not always freed because some processes would still stay alive in the background. I needed to manually run `kill -9 PID` to stop them and free the memory (after using htop to find the zombie processes). However the memory use was not evolving anymore once the program was stopped.

I was assuming some memory leaks because the allocated memory keeps growing. In a perfect scenario, it would be cyclic, and should not lead to an overall increase between each parquet file being processed.

**Comment by mmcdermott** [comment]
Ok, so the memory leak is independent of the zombie processes. @Oufattole, does this resonate with your recollection at all? I know you had been monitoring memory usage more extensively.

**Comment by florian6973** [comment]
From my latest experiments, the polars version seems to play a major role regarding memory consumption. I wonder if it may be related to the polars library. I was still running with polars 1.17.1

**Comment by mmcdermott** [comment]
@Oufattole , can you weigh in here, even just in your past experiences profiling things more extensively?

**Comment by mmcdermott** [comment]
Also, @florian6973 , is this issue solved with polars 1.26, as the current pyproject.toml requires?

**Comment by Oufattole** [comment]
This memory usage creeping up over time matches what I saw when I recorded the memory usage for runs. I tried manually calling garbage collection gc.collect() after processing each file and using `del` on various objects, but that did not resolve this.

The lifespan of a worker is for a for loop through all the aggregations and window sizes ([link to for loop](https://github.com/mmcdermott/MEDS_Tabular_AutoML/blob/aeee6f5c4ca552d51295362ff46b1bc4288b311f/src/MEDS_tabular_automl/scripts/tabularize_time_series.py#L85)). This means that memory is not deallocated until a worker completes this for loop, which happens after all output files (for all aggregation functions and window sizes) are either created or locked by a different worker. A temporary solution is to have a bash for loop that launches `meds-tab-tabularize-time-series` for a single window size and/or aggregation at a time so worker memory is deallocated after all files for a single window size and/or aggregation are complete instead of after all are completed by the pool. This is a temporary solution, but maybe we should modify this script to leverage joblib via hydra to launch separate workers per aggregation and window size so joblib handles deallocating memory.
